<?php

use Illuminate\Database\Seeder;

class IndustriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('industries')->insert([
            'name'=>'食品・飲料'
        ]);
        DB::table('industries')->insert([
            'name'=>'繊維'
        ]);
        DB::table('industries')->insert([
            'name'=>'アパレル'
        ]);
        DB::table('industries')->insert([
            'name'=>'化粧品・医薬'
        ]);
        DB::table('industries')->insert([
            'name'=>'医療・福祉・介護'
        ]);
        DB::table('industries')->insert([
            'name'=>'電機・自動車'
        ]);
        DB::table('industries')->insert([
            'name'=>'化学・石油'
        ]);
        DB::table('industries')->insert([
            'name'=>'住宅・建設'
        ]);
        DB::table('industries')->insert([
            'name'=>'不動産'
        ]);
        DB::table('industries')->insert([
            'name'=>'旅行'
        ]);
        DB::table('industries')->insert([
            'name'=>'ホテル・レジャー'
        ]);
        DB::table('industries')->insert([
            'name'=>'卸売・小売'
        ]);
        DB::table('industries')->insert([
            'name'=>'サービス'
        ]);
        DB::table('industries')->insert([
            'name'=>'商社'
        ]);
        DB::table('industries')->insert([
            'name'=>'人材・教育'
        ]);
        DB::table('industries')->insert([
            'name'=>'コンサルティング'
        ]);
        DB::table('industries')->insert([
            'name'=>'広告'
        ]);
        DB::table('industries')->insert([
            'name'=>'マスコミ'
        ]);
        DB::table('industries')->insert([
            'name'=>'出版・印刷'
        ]);
        DB::table('industries')->insert([
            'name'=>'IT'
        ]);
        DB::table('industries')->insert([
            'name'=>'ゲーム'
        ]);
        DB::table('industries')->insert([
            'name'=>'ソフトフェア'
        ]);
        DB::table('industries')->insert([
            'name'=>'銀行・信金'
        ]);
        DB::table('industries')->insert([
            'name'=>'投資(PE・VC・ヘッジファンド)'
        ]);
        DB::table('industries')->insert([
            'name'=>'クレジットカード'
        ]);
        DB::table('industries')->insert([
            'name'=>'証券'
        ]);
        DB::table('industries')->insert([
            'name'=>'保険'
        ]);
        DB::table('industries')->insert([
            'name'=>'インフラ'
        ]);
        DB::table('industries')->insert([
            'name'=>'鉄道・航空'
        ]);
        DB::table('industries')->insert([
            'name'=>'運輸・物流'
        ]);
        DB::table('industries')->insert([
            'name'=>'農林・水産'
        ]);
        DB::table('industries')->insert([
            'name'=>'官公庁'
        ]);
        DB::table('industries')->insert([
            'name'=>'国際機関'
        ]);
        DB::table('industries')->insert([
            'name'=>'弁護士・行政書士'
        ]);
        DB::table('industries')->insert([
            'name'=>'その他'
        ]);
    }
}
